import { MigrationInterface, QueryRunner } from "typeorm";

export class FixMigration1738165639044 implements MigrationInterface {
    name = 'FixMigration1738165639044'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "order_data" DROP CONSTRAINT "fk_orderdata_order"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "fk_cart_user"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cartitem_cart"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "fk_cartitem_product"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "fk_product_category"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "fk_orderproduct_order"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "fk_orderproduct_product"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "fk_order_user"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "pickuppoint"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP CONSTRAINT "order_data_orderid_key"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "orderid"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "carts_userid_key"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP COLUMN "userid"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "cartid"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "productid"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "categoryid"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "orderid"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "productid"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "userid"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentmethodid"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "pickupPoint" integer`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "orderId" integer`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD CONSTRAINT "UQ_45550d0c6b37872c93f7922da35" UNIQUE ("orderId")`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "cartId" integer`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "productId" integer`);
        await queryRunner.query(`ALTER TABLE "products" ADD "categoryId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "orderId" integer`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "productId" integer`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentMethodId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "userId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD "credentialId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_d6d50143a16c49c49bf467ae541" UNIQUE ("credentialId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "cartId" integer`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_89502c44bd22c06e714c31c1e93" UNIQUE ("cartId")`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "password" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "description" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "price" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "products_slug_key"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "slug" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "date" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_email_key"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "address" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'user')`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" "public"."users_role_enum" NOT NULL DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD CONSTRAINT "FK_45550d0c6b37872c93f7922da35" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_72679d98b31c737937b8932ebe6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_28b66449cf7cd76444378ad4e92" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "FK_27ca18f2453639a1cafb7404ece" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_d6d50143a16c49c49bf467ae541" FOREIGN KEY ("credentialId") REFERENCES "credentials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_89502c44bd22c06e714c31c1e93" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_89502c44bd22c06e714c31c1e93"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_d6d50143a16c49c49bf467ae541"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_27ca18f2453639a1cafb7404ece"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP CONSTRAINT "FK_28b66449cf7cd76444378ad4e92"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_72679d98b31c737937b8932ebe6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP CONSTRAINT "FK_45550d0c6b37872c93f7922da35"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "role"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "role" character varying(20) DEFAULT 'user'`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "phone" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "address" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_email_key" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ALTER COLUMN "date" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "slug"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "slug" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "products_slug_key" UNIQUE ("slug")`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "image"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "image" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "price"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "price" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "description" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "categories" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "categories" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "email" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "address"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "address" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "phone" character varying(20) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "credentials" DROP COLUMN "password"`);
        await queryRunner.query(`ALTER TABLE "credentials" ADD "password" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_89502c44bd22c06e714c31c1e93"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "cartId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_d6d50143a16c49c49bf467ae541"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "credentialId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentMethodId"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "order_products" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "categoryId"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP COLUMN "cartId"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP CONSTRAINT "UQ_45550d0c6b37872c93f7922da35"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "orderId"`);
        await queryRunner.query(`ALTER TABLE "order_data" DROP COLUMN "pickupPoint"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentmethodid" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "userid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "productid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD "orderid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "products" ADD "categoryid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "productid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD "cartid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "carts" ADD "userid" integer`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "carts_userid_key" UNIQUE ("userid")`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "orderid" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD CONSTRAINT "order_data_orderid_key" UNIQUE ("orderid")`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD "pickuppoint" integer`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "fk_order_user" FOREIGN KEY ("userid") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "fk_orderproduct_product" FOREIGN KEY ("productid") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_products" ADD CONSTRAINT "fk_orderproduct_order" FOREIGN KEY ("orderid") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "fk_product_category" FOREIGN KEY ("categoryid") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cartitem_product" FOREIGN KEY ("productid") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "fk_cartitem_cart" FOREIGN KEY ("cartid") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "fk_cart_user" FOREIGN KEY ("userid") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_data" ADD CONSTRAINT "fk_orderdata_order" FOREIGN KEY ("orderid") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
